package main

import (
	"io/ioutil"
	"os"
	"regexp"
	"strconv"
	"strings"
)
import "fmt"
import "mapreduce"

// The mapping function is called once for each piece of the input.
// In this framework, the key is the name of the file that is being processed,
// and the value is the file's contents. The return value should be a slice of
// key/value pairs, each represented by a mapreduce.KeyValue.
func mapFi(document string, value string) (res []mapreduce.KeyValue) {
	// TODO: you should complete this to do the inverted index challenge
	words := ReadWord(value)
	wm := make(map[string]*mapreduce.KeyValue)
	//word file
	for _, w := range words {
		w = strings.Trim(w, "_")
		if wm[w] == nil {
			kv := new(mapreduce.KeyValue)
			kv.Key = w
			kv.Value = document
			wm[w] = kv
			res = append(res, *kv)
		}
	}
	return res
}


// The reduce function is called once for each key generated by Map, with a
// list of that key's string value (merged across all inputs). The return value
// should be a single output value for that key.
func reduceFi(key string, values []string) string {
	// TODO: you should complete this to do the inverted index challenge
	str := strconv.Itoa(len(values))
	for _, v := range values {
		str += " " + v
	}
	return str
}
//TODO  以文件方式运行（打包），包中的其他带有main函数的文件，不能同时被编译，因此声明的函数无法公用，需要另外声明在其他文件
func ReadWord(str string) []string{
	exp := regexp.MustCompile(`\w+`)
	return exp.FindAllString(str, -1)
}
func GetExpFiles(pattern string) (res []string) {
	exp := regexp.MustCompile(pattern)
	wd, _ := os.Getwd()
	fileInfos, _ := ioutil.ReadDir(wd)
	for _, fi := range fileInfos {
		if exp.MatchString(fi.Name()) {
			res = append(res, fi.Name())
		}
	}
	return res
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) Master (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
//	go run ii.go master localhost:7777 pg-.*.txt
//	go run ii.go worker localhost:7777 localhost:7778
//	go run ii.go worker localhost:7777 localhost:7779
//	go run ii.go worker localhost:7777 localhost:7780
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("iiseq", GetExpFiles(os.Args[3]), 3, mapFi, reduceFi)
		} else {
			mr = mapreduce.Distributed("iiseq", GetExpFiles(os.Args[3]), 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], mapFi, reduceFi, 100)
	}
}
